#!/usr/bin/sh
#
# ~/.uncommonrc
#
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export PYTHONSTARTUP=$HOME/.pythonstartup
export HTTP_PROXY=10.66.243.130:8080
export HTTPS_PROXY=10.66.243.130:8080
export FTP_PROXY=10.66.243.130:8080
export NO_PROXY=localhost,sagem

export http_proxy=http://10.66.243.130:8080
export https_proxy=http://10.66.243.130:8080
export ftp_proxy=http://10.66.243.130:8080
export no_proxy=localhost,sagem

#======================================================
# aliases
#======================================================

### Aliases pbuilder
alias base.lucid='sudo pbuilder --create --configfile /etc/pbuilderrc.lucid'
alias base.lucid.64='sudo pbuilder --create --configfile /etc/pbuilderrc.lucid-64'
alias base.maverick='sudo pbuilder --create --configfile /etc/pbuilderrc.maverick'
alias base.maverick.64='sudo pbuilder --create --configfile /etc/pbuilderrc.maverick-64'
alias base.natty='sudo pbuilder --create --configfile /etc/pbuilderrc.natty'
alias base.natty.64='sudo pbuilder --create --configfile /etc/pbuilderrc.natty-64'
alias base.oneiric='sudo pbuilder --create --configfile /etc/pbuilderrc.oneiric'
alias base.oneiric.64='sudo pbuilder --create --configfile /etc/pbuilderrc.oneiric-64'

### Aliases pdebuild
# aliases without signatures
alias build.lucid='sudo pdebuild --configfile /etc/pbuilderrc.lucid'
alias build.lucid.64='sudo pdebuild --configfile /etc/pbuilderrc.lucid-64'
alias build.maverick='sudo pdebuild --configfile /etc/pbuilderrc.maverick'
alias build.maverick.64='sudo pdebuild --configfile /etc/pbuilderrc.maverick-64'
alias build.natty='sudo pdebuild --configfile /etc/pbuilderrc.natty'
alias build.natty.64='sudo pdebuild --configfile /etc/pbuilderrc.natty-64'
alias build.oneiric='sudo pdebuild --configfile /etc/pbuilderrc.oneiric'
alias build.oneiric.64='sudo pdebuild --configfile /etc/pbuilderrc.oneiric-64'
