#!/bin/sh

allfileshas=$(git rev-list --objects --all | sort -k 2)
git gc >/dev/null 2>&1
bigobjects=$(git verify-pack -v .git/objects/pack/pack-*.idx | egrep '^\w+ blob\W+[0-9]+ [0-9]+ [0-9]+$' | sort -k 3 -n -r)
for SHA in $(echo "$bigobjects" | cut -f 1 -d' ' | head); do
    echo $(echo "$bigobjects" | grep $SHA) $(echo "$allfileshas" | grep $SHA) | awk '{print $3,$7}';
done

