#!/bin/sh

if [ $# != 1 ]; then
    echo "Usage: $0 <filename>"
    exit 1
fi

filename=$1
git filter-branch -f --prune-empty --index-filter "git rm -rf --cached --ignore-unmatch ${filename}" --tag-name-filter cat -- --all
